updated the yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-name: Weather Pipelin CI/CD (JS)
+name: Weather Pipeline CI/CD (JS)
 
 on:
   push:
@@ -25,20 +25,20 @@ jobs:
             path: ~/.npm
             key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
       - name: Install Dependencies
-        run: npm ci 
-      - name: Fetch latest weather
-        env: 
+        run: npm ci
+      - name: Fetch latest Weather
+        env:
           WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
           CITY: ${{ secrets.CITY }}
         run: node fetchWeather.js
       - name: Run tests
         run: npm test
-      - name: Commit weather data if it changes 
-        run: 
+      - name: Commit weather data if it changes
+        run: |
           git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add data/weather.json data/weather_Log.csv || true
-          git commit -m "ci update weather data" || echo "no changes to commit"
-          git push || echo "push failed or not changes"
-      - name: Trigger Rendor Deploy
+          git config user.email "github-action[bot]@users.noreply.github.com"
+          git add data/weather.json data/weather_log.csv || true
+          git commit -m "ci: update weather data" || echo "no changes to commit"
+          git push || echo 'push failed or no changes'
+      - name: Trigger Render Deploy
         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
